### PR TITLE
Explain tests in more detail

### PR DESCRIPTION
**Pull request by SteveBarnett**
I've noticed a few coders writing tests that chain inputs: they don't have small, focused, tests that only look at once function. The idea is to have a short demo / workshop talking through the ideas, then tell them that a summary is written up as a Tip.

@avermeulen, @Onwa2014, @Oyamasiphula please take a 👀 .

### CODE REVIEW

**Comment by avermeulen** [comment]
@SteveBarnett looks funky. One observation - should we add the test that you mention at the bottom that should be added?

**Comment by SteveBarnett** [comment]
@avermeulen I've added the other test, but I'm thinking about revisiting this and: making it more realistic; not showing the actual functions (I think they just add noise, and we want to focus on the tests).

**Comment by avermeulen** [comment]
@SteveBarnett yes - not having the examples might be better as you mention as the concept is more important than a specific example. A fine line... but it should work here. Maybe keep you example for a workshop/session about testing.

**Comment by SteveBarnett** [comment]
Going to do a workshop-y like thing instead.

**Pull request closed without merging**
