### PR TITLE
Add ESLint tip

### PR DESCRIPTION
**Pull request by SteveBarnett**
@avermeulen what do you reckon?

ESLint gives three options when running `eslint --init`:
- Answer questions about your style;
- Use a popular style guide;
- Inspect your JavaScript file(s)

The second two seem a bit more fiddly to me. Although the I really <3 the AirBnB settings: they are nicely harsh. Maybe combined with the auto-fix in the atom linter it's not so bad?

### CODE REVIEW

**Comment by avermeulen** [comment]
That is quite a complicated setup in the Daily Tip. :-( How do we use the AirBnB one by default? @SteveBarnett

**Comment by avermeulen** [comment]
The instructions assumes that `eslint` is available globally. Which makes eslint very unhappy.

Locally I can only run it like this: `node_modules/.bin/eslint --init` after I did a local install. @SteveBarnett are you replacing this section with gulp or should we change this accordingly with a local path or a npm task and publish it?

**Comment by SteveBarnett** [comment]
@avermeulen I think it'll be easier to do with gulp. But. We'll have to build up to it.
1. Gulp. 
2. Gulp with combine and concat JS and CSS.
3. Gulp with ESLint.

Maybe switching 2 and 3.

**Comment by avermeulen** [comment]
@SteveBarnett They already have gulp installed locally for 53functions. So that is step one covered.

**Comment by SteveBarnett** [comment]
As discussed, we're going to roll this into a Gulp thing.

**Pull request closed without merging**
